### ISSUE TITLE
Failure to run CICERO

### ISSUE THREAD

**Issue by maximus3219** [stjude/CICERO#119]
I try running Cicero either locally or using Docker, and it just stuck at "Step 01 - 2023.12.02 17:53:45 - ExtractSClips", without any progression. The bam file is just from a targeted RNA-seq, and running STAR-fusion and Arriba just takes less than 10 minutes. 
What has gone wrong? Is that it depends on the blat server? Anyway to correct this?

The code:
Cicero.sh -b /media/Data/RNA-seq/Bam/08AH9897/Aligned.sortedByCoord.out.bam -r /media/Data/Reference/Cicero/reference -g GRCh38_no_alt -j /media/Data/RNA-seq/Bam/08AH9897/Aligned.sortedByCoord.out.bam.junctions.tab.shifted.tab -O /media/Data/RNA-seq/Bam/08AH9897 -p -n 8

docker:
docker run -v $OUTDIR:/input -v $REFDIR:/reference ghcr.io/stjude/cicero:latest -n 8 -b /input/Aligned.sortedByCoord.out.bam -g GRCh38_no_alt -r /reference -j /input/Aligned.sortedByCoord.out.bam.junctions.tab.shifted.tab -o /input/Cicero -s 2 -no-optimize

Thanks.

**Comment by adthrasher** [comment]
Can you share the output? The `Cicero.sh` script attempts to start a BLAT server that the downstream steps will then query. Since you see logging output that `Step 01` has started, the BLAT server should have already been successfully started. You can also check the running processes (using something like `ps` and if running with a container `docker exec`). How long has step 1 been running?
