### ISSUE TITLE
Failure to run docker for rnapeg. 

### ISSUE THREAD

**Issue by jdjdj0202** [stjude/CICERO#120]
Hi, 
I am trying to analyze RNA fusion using CICERO.
I am using MacBook terminal. 

I ran the following command line:
------------------------------------------------------------------------------------------------
docker pull ghcr.io/stjude/cicero:latest --platform linux/amd64 
------------------------------------------------------------------------------------------------

And then, 
------------------------------------------------------------------------------------------------
docker run -v /Users/dajeong/CICERO_DJ:/results ghcr.io/stjude/rnapeg:latest --platform linux/amd64 \
-b /results/ATL005_STAR_Aligned.out.bam \
-f /results/hg38.fa \
-r /results/refFlat.txt
------------------------------------------------------------------------------------------------

The error messages are as follows:
------------------------------------------------------------------------------------------------
Unable to find image 'ghcr.io/stjude/rnapeg:latest' locally
latest: Pulling from stjude/rnapeg
docker: no matching manifest for linux/arm64/v8 in the manifest list entries.
See 'docker run --help'.
------------------------------------------------------------------------------------------------

Please help me. 
Thanks! 

Sincerely,
DJ. J

**Comment by adthrasher** [comment]
Hello, 

It appears that you are using a macbook with Apple silicon, so Docker is trying to pull a matching container ("linux/arm64/v8"). I see that you've specificied a `--platform linux/amd64` argument. The issue is where you've placed it. In the Docker `pull`, it must precede the image name like this:

```
docker pull --platform linux/amd64 ghcr.io/stjude/cicero:latest
```

Similarly for the Docker `run` command, it must also precede the image name like this:

```
docker run -v /Users/dajeong/CICERO_DJ:/results --platform linux/amd64 ghcr.io/stjude/rnapeg:latest
-b /results/ATL005_STAR_Aligned.out.bam
-f /results/hg38.fa
-r /results/refFlat.txt
```

Please let me know if you encounter any further issues.
